README.md
【Kaggle卫星图像船舶检测比赛第八名方案】“Kaggle Airbus Ship Detection Challenge 2018 8th place code” by Tao.Shen GitHub:http://t.cn/E2vf2UX ​
=> Add Kaggle卫星图像船舶检测比赛第八名方案

README.md
add 'BDCI2018联通赛题第一名解决方案' by PPshrimpGo GitHub: http://t.cn/E22Q7KZ ​
=> Add BDCI2018联通赛题第一名解决方案

README.md
ADD:
- 2018 CCF-汽车领域ASC挑战赛Rank7
- 2018 CCL 客服领域用户意图分类评测Rank1
- 第二届搜狐内容识别大赛Rank1
=> Add 3 competitions

README.md
Kaggle 2017 Santa competition and achieved 54th place.
https://github.com/bigzhao/MPI-Hungarian-method
Porto Seguro’s Safe Driver Prediction
在 5,169 个参赛队伍中排名第 131 位（top3% 夺银）
https://bigzhao.github.io/2017/12/18/kaggle-silver/
=> Add Kaggle 2 competitions

README.md
1. 联通研究院-面向电信行业存量用户的智能套餐个性化匹配模型_复赛第6名
2. 2017腾讯广告算法大赛 Rank14 + Rank20
3. 第二届 “智慧中国杯” 数据科学大赛，首发皇包车（HI GUIDES）精品旅行服务成单预测竞赛   Rank4 + ?
=> add 5 solutions

README.md
DataCastle-城市治理大数据应用创意方案赛 冠军代码
=> add DataCastle-城市治理大数据应用创意方案赛 冠军代码

README.md
https://github.com/ziweipolaris/atec2018-nlp
=> add 2018年蚂蚁金服金融大脑赛题分享 复赛f1 = 0.7327

README.md
Kaggle - Crowdflower Search Results Relevance
=> add Kaggle Crowdflower Search Results Relevance rank 1 and 第三届融360天机智能金融算法挑战赛 - 特征挖掘  rank1

README.md
=> add 摩拜杯 算法挑战赛 第三名 解决方案

README.md
BDCI 2018 汽车行业用户观点主题及情感识别 决赛一等奖方案
https://github.com/yilirin/BDCI_Car_2018
=> add BDCI 2018 汽车行业用户观点主题及情感识别 决赛一等奖方案

README.md
招商银行信用卡中心 消费金融场景下的用户购买预测 rank1
=> add a solution

README.md
- 天池糖尿病血糖预测比赛 精准医疗 初赛B榜24名
- 百度机器阅读理解竞赛 3rd 解决方案
=> add 2 solutions

README.md
https://github.com/jinchenyu/2018_CCF_BDCI_ChinaUicom_rank4_solution
=> add 2018 CCF BDCI 面向电信行业存量用户的智能套餐个性化匹配模型 rank4

README.md
4th place solution for 2018 Data Science Bowl kaggle competition
=> add repo for 4th place solution for 2018 Data Science Bowl

README.md
2017 CCF-商场中精确定位用户所在店铺
Rank1：https://github.com/drop-out/Tianchi-Wifi-Positioning
=> add 2017 CCF-商场中精确定位用户所在店铺 rank1

README.md
【Kaggle卫星图像船舶检测比赛21名方案】’Kaggle Airbus Ship Detection Challenge : 21st solution' by Pascal GitHub: http://t.cn/EUyOWAM ​
=> add Kaggle卫星图像船舶检测比赛21名方案

README.md
ai challenger 2018细粒度情感分类第一名解决方案
https://github.com/chenghuige/wenzheng
=> ai challenger 2018细粒度情感分类第一名解决方案

README.md
【Kaggle PLAsTiCC天文分类比赛第四名方案】’4th Place Solution to PLAsTiCC Astronomical Classification Competition
' by Ahmet Erdem GitHub: http://t.cn/E4n4LH7 ref:http://t.cn/E4n4LHP ​
=> add Kaggle PLAsTiCC天文分类比赛 rank1-5

README.md
kaggle-hpa - Code for 3rd place solution in Kaggle Human Protein Atlas Image Classification Challenge.' by pudae 
GitHub: http://t.cn/E51p9Sb
=> add Kaggle人类蛋白质图谱图像分类比赛第三名方案

README.md
https://github.com/Dikea/Dialog-System-with-Task-Retrieval-and-Seq2seq
=> add 2018 JDDC对话大赛亚军解决方案

README.md
'ocr_densenet - 第一届西安交通大学人工智能实践大赛（2018AI实践大赛--图片文字识别）第一名；仅采用densenet识别图中文字' by yinchangchang GitHub: http://t.cn/Etm1VNF ​
=> add 第一届西安交通大学人工智能实践大赛（2018AI实践大赛--图片文字识别）第一名

README.md
https://github.com/SpaceNetChallenge/SpaceNet_Off_Nadir_Solutions
=> SpaceNet挑战卫星图片建筑物识别优胜方案

README.md
Kaggle Humpback Whale Identification Challenge（Kaggle座头鲸识别比赛第一名方案）   
- Rank1: https://github.com/earhian/Humpback-Whale-Identification-1st-   
- Rank7: https://medium.com/@ducha.aiki/thanks-radek-7th-place-solution-to-hwi-2019-competition-738624e4c885
=> Add Kaggle座头鲸识别比赛第一名和第七名方案

README.md
https://github.com/qrfaction/1st-Freesound-Audio-Tagging-2019
=> Kaggle Freesound Audio Tagging 2019 1st place code
